virtual_cemetery/about/urls.py
import django.urls

import about.views

app_name = "about"

urlpatterns = [
    django.urls.path("", about.views.about_view, name="about"),
]

virtual_cemetery/event/urls.py
import django.urls

import event.views

app_name = "event"

urlpatterns = [
    django.urls.path("all/", event.views.all_events_view, name="all-events"),
    django.urls.path("register/", event.views.registration_event_work, name="register-work"),
    django.urls.path("work/<int:pk>/", event.views.get_current_work_event, name="current-work"),
    django.urls.path("<int:pk>/", event.views.get_current_event_view, name="current-event"),
]

virtual_cemetery/faq/urls.py
import django.urls

import faq.views

app_name = "faq"

urlpatterns = [
    django.urls.path("", faq.views.faq_view, name="faq"),
]

virtual_cemetery/feedback/urls.py
import django.urls

import feedback.views

app_name = "feedback"

urlpatterns = [
    django.urls.path("", feedback.views.feedback_view, name="feedback"),
]

virtual_cemetery/users/urls.py
import django.contrib.auth.views as auth_views
import django.forms
import django.urls


import users.forms
import users.views

app_name = "users"

urlpatterns = [
    django.urls.path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="users/login/login.html",
            authentication_form=users.forms.AuthForm,
        ),
        name="login",
    ),
    django.urls.path(
        "logout/",
        auth_views.LogoutView.as_view(
            template_name="users/login/logout.html",
        ),
        name="logout",
    ),
    django.urls.path(
        "password-reset/",
        users.views.CustomPasswordResetView.as_view(
            template_name="users/reset_password/password_reset_form.html",
            email_template_name="users/reset_password/sent_mail/password_reset_email.html",
            subject_template_name="users/reset_password/sent_mail/password_reset_subject.txt",
            success_url=django.urls.reverse_lazy(
                "users:password-reset-done",
            ),
        ),
        name="password-reset",
    ),
    django.urls.path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/reset_password/password_reset_done.html",
        ),
        name="password-reset-done",
    ),
    django.urls.path(
        "password-reset/confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="users/reset_password/password_reset_confirm.html",
            success_url=django.urls.reverse_lazy(
                "users:password-reset-complete",
            ),
        ),
        name="password-reset-confirm",
    ),
    django.urls.path(
        "password-reset/complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/reset_password/password_reset_complete.html",
        ),
        name="password-reset-complete",
    ),
    django.urls.path(
        "password-change/",
        users.views.CustomPasswordChangeView.as_view(
            template_name="users/change_password/password_change.html",
            success_url=django.urls.reverse_lazy(
                "users:password-change-done",
            ),
        ),
        name="password-change",
    ),
    django.urls.path(
        "password-change/done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="users/change_password/password_change_done.html",
        ),
        name="password-change-done",
    ),
    django.urls.path("profile/", users.views.profile_user, name="profile"),
    django.urls.path("profile/settings/", users.views.profile_user_change, name="profile_settings"),
    django.urls.path("signup/", users.views.SignUpView.as_view(), name="signup"),
    django.urls.path("activate/<pk>/", users.views.activate, name="activate"),
    django.urls.path("reactivate/<pk>/", users.views.reactivate, name="reactivate"),
    django.urls.path(
        "resend_activation_email",
        users.views.resend_activation_email,
        name="resend_activation_email",
    ),
    django.urls.path("user-profile/<pk>/", users.views.profile_user_view, name="profile-user"),
    django.urls.path("donate/", users.views.donate_view, name="donate"),
]

virtual_cemetery/virtual_cemetery/urls.py
import django.contrib
import django.urls
import django.views

urlpatterns = [
    django.urls.path("admin/", django.contrib.admin.site.urls),
    django.urls.path("", django.urls.include("homepage.urls")),
    django.urls.path("about/", django.urls.include("about.urls")),
    django.urls.path("animals/", django.urls.include("animals.urls")),
    django.urls.path("users/", django.urls.include("users.urls")),
    django.urls.path("event/", django.urls.include("event.urls")),
    django.urls.path("faq/", django.urls.include("faq.urls")),
    django.urls.path("feedback/", django.urls.include("feedback.urls")),
    django.urls.path(
        "set-language/",
        django.views.i18n.set_language,
        name="set-language",
    ),
]

if django.conf.settings.DEBUG:
    import debug_toolbar
    import django.conf.urls.static

    STATIC_ROOT = django.conf.urls.static.static

    urlpatterns += (
        [
            django.urls.path(
                "__debug__/",
                django.urls.include(debug_toolbar.urls),
            ),
        ]
        + STATIC_ROOT(
            django.conf.settings.STATIC_URL,
            document_root=django.conf.settings.STATICFILES_DIRS,
        )
        + STATIC_ROOT(
            django.conf.settings.MEDIA_URL,
            document_root=django.conf.settings.MEDIA_ROOT,
        )
    )

virtual_cemetery/templates/includes/footer.html
<!DOCTYPE html>
{% load static %}
<footer class="py-3 my-4">
  <div class="container">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item">
        <a href="{% url 'homepage:home' %}" class="nav-link px-2 text-body-secondary">Главная</a>
      </li>
      <li class="nav-item">
        <a href="{% url 'feedback:feedback' %}" class="nav-link px-2 text-body-secondary">Обратная связь</a>
      </li>
      <li class="nav-item">
        <a href="{% url 'users:profile' %}" class="nav-link px-2 text-body-secondary">Личный кабинет</a>
      </li>
      <li class="nav-item">
        <a href="{% url 'about:about' %}" class="nav-link px-2 text-body-secondary">О нас</a>
      </li>
      <li class="nav-item">
        <a href="{% url 'faq:faq' %}" class="nav-link px-2 text-body-secondary">FAQ</a>
      </li>
      <li class="nav-item">
        <a href="{% url 'users:donate' %}" class="nav-link px-2 text-body-secondary">Пожертвование</a>
      </li>
      <li class="nav-item">
        <a href="{% url 'event:all-events' %}" class="nav-link px-2 text-body-secondary">Конкурсы</a>
      </li>

    </ul>
    <p class="text-center text-body-secondary">&copy; 2024 - {% now "Y" %} cloudpets</p>
  </div>
</footer>

virtual_cemetery/templates/includes/form.html
<!DOCTYPE html>
{% load i18n %}
{% load static %}

{% for field in form  %}
<div>
    {% for error in field.errors %}
        <div class="alert alert-danger">
            {{ error | escape }}
        </div>
    {% endfor %}

    {{ field.label_tag }} {{ field }}
    {% if field.help_text %}
        <p class="help">{{ field.help_text | safe }} </p>
    {% endif %}
</div>
{% endfor %}

virtual_cemetery/templates/includes/header.html
<!DOCTYPE html>
{% load static %}

<header class="p-3 text-white header js-header" style="background-color: #000000;">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-between" style="font-weight: bold;">
            {% with request.resolver_match.view_name as view_name %}
            <div class="nav-link-block"> 
                <a class="navbar-brand mr-1" href="{% url 'homepage:home' %}" style="margin-right:30px;">
                    <img src="{% static 'img/cloudpets-header-logo1.png' %}" alt="Logo" width="50" height="50">
                </a>
                {% if view_name == 'homepage:home' %}
                    <span class="nav-link px-2 text-white underline disabled nav-box ">Главная</span>
                {% else %}
                    <a class="nav-link px-2 text-white nav-box" href="{% url 'homepage:home' %}">Главная</a>
                {% endif %}
                {% if view_name == 'event:all-events' %}
                    <span class="nav-link px-2 text-white underline disabled nav-box">Конкурсы</span>
                {% else %}
                    <a class="nav-link px-2 text-white nav-box" href="{% url 'event:all-events' %}">Конкурсы</a>
                {% endif %}
                {% if view_name == 'faq:faq' %}
                    <span class="nav-link px-2 text-white underline disabled nav-box">FAQ</span>
                {% else %}
                    <a class="nav-link px-2 text-white nav-box" href="{% url 'faq:faq' %}">FAQ</a>
                {% endif %}
                {% if view_name == 'about:about' %}
                    <span class="nav-link px-2 text-white underline disabled nav-box">О нас</span>
                {% else %}
                    <a class="nav-link px-2 text-white nav-box" href="{% url 'about:about' %}">О нас</a>
                {% endif %}
                {% if user.is_authenticated %}
                    {% if view_name == 'feedback:feedback' %}
                        <span class="nav-link px-2 text-white underline disabled nav-box">Обратная связь</span>
                    {% else %}
                        <a class="nav-link px-2 text-white nav-box" href="{% url 'feedback:feedback' %}">Обратная связь</a>
                    {% endif %}
                    {% if view_name == 'users:profile' %}
                        <span class="nav-link px-2 text-white underline disabled nav-box">Личный кабинет</span>
                    {% else %}
                        <a class="nav-link px-2 text-white nav-box" href="{% url 'users:profile' %}">Личный кабинет</a>
                    {% endif %}
                {% endif %}
                {% if view_name == 'users:donate' %}
                    <button class="btn btn-outline-secondary disabled" type="button">Пожертвование</button>
                {% else %}
                    <a class="btn btn-outline-light" href="{% url 'users:donate' %}">Пожертвование</a>
                {% endif %}
            </div>
            <div class="nav-link-block">
                {% if user.is_authenticated %}
                    {% if user.is_superuser %}
                        <a class="nav-link px-2 text-white nav-box {% if view_name == 'admin:index' %}active{% endif %}" href="{% url 'admin:index' %}">Админ-панель</a>
                    {% endif %}
                    {% if view_name == 'animals:add-animal' %}
                        <button class="btn btn-outline-secondary disabled" type="button">Создать пост</button>
                    {% else %}
                        <a class="btn btn-outline-primary" href="{% url 'animals:add-animal' %}">Создать пост</a>
                    {% endif %}
                    <form action="{% url 'users:logout' %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-light">Выйти</button>
                    </form>
                {% else %}
                    <button type="button" class="btn btn-outline-light" onclick="location.href='{% url 'users:login' %}';">Войти</button>
                    <button type="button" class="btn btn-outline-info" onclick="location.href='{% url 'users:signup' %}';">Регистрация</button>
                {% endif %}
            </div>
            {% endwith %}
        </div>
    </div>
</header>

virtual_cemetery/templates/includes/messages.html
<!DOCTYPE html>
{% load i18n %}
{% load static %}

{% if messages %}
  {% for message in messages %}
    {% if message.tags == 'error' %}
      <div class="alert alert-danger" role="alert">
        {{ message }}
      </div>
    {% elif message.tags == 'warning' %}
      <div class="alert alert-warning" role="alert">
        {{ message }}
      </div>
    {% elif message.tags == 'info' %}
      <div class="alert alert-info" role="alert">
        {{ message }}
      </div>
    {% else %}
      <div class="alert alert-success" role="alert">
        {{ message }}
      </div>
    {% endif %}
  {% endfor %}
{% endif %}