virtual_cemetery/animals/urls.py
import django.urls

import animals.views

app_name = "animals"

urlpatterns = [
    django.urls.path("detail/<pk>/", animals.views.animal_detail, name="animal-detail"),
    django.urls.path("add-new-animal/", animals.views.add_new_animal, name="add-animal"),
    django.urls.path("change/<pk>/", animals.views.change_current_animal, name="change-animal"),
    django.urls.path("delete-comment/<pk>/", animals.views.delete_comment, name="delete-comment"),
    django.urls.path("delete-animal/<pk>/", animals.views.delete_animal, name="delete-animal"),
]

virtual_cemetery/faq/urls.py
import django.urls

import faq.views

app_name = "faq"

urlpatterns = [
    django.urls.path("", faq.views.faq_view, name="faq"),
]

virtual_cemetery/users/urls.py
import django.contrib.auth.views as auth_views
import django.forms
import django.urls


import users.forms
import users.views

app_name = "users"

urlpatterns = [
    django.urls.path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="users/login/login.html",
            authentication_form=users.forms.AuthForm,
        ),
        name="login",
    ),
    django.urls.path(
        "logout/",
        auth_views.LogoutView.as_view(
            template_name="users/login/logout.html",
        ),
        name="logout",
    ),
    django.urls.path(
        "password-reset/",
        users.views.CustomPasswordResetView.as_view(
            template_name="users/reset_password/password_reset_form.html",
            email_template_name="users/reset_password/sent_mail/password_reset_email.html",
            subject_template_name="users/reset_password/sent_mail/password_reset_subject.txt",
            success_url=django.urls.reverse_lazy(
                "users:password-reset-done",
            ),
        ),
        name="password-reset",
    ),
    django.urls.path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/reset_password/password_reset_done.html",
        ),
        name="password-reset-done",
    ),
    django.urls.path(
        "password-reset/confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="users/reset_password/password_reset_confirm.html",
            success_url=django.urls.reverse_lazy(
                "users:password-reset-complete",
            ),
        ),
        name="password-reset-confirm",
    ),
    django.urls.path(
        "password-reset/complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/reset_password/password_reset_complete.html",
        ),
        name="password-reset-complete",
    ),
    django.urls.path(
        "password-change/",
        users.views.CustomPasswordChangeView.as_view(
            template_name="users/change_password/password_change.html",
            success_url=django.urls.reverse_lazy(
                "users:password-change-done",
            ),
        ),
        name="password-change",
    ),
    django.urls.path(
        "password-change/done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="users/change_password/password_change_done.html",
        ),
        name="password-change-done",
    ),
    django.urls.path("profile/", users.views.profile_user, name="profile"),
    django.urls.path("profile/settings/", users.views.profile_user_change, name="profile_settings"),
    django.urls.path("signup/", users.views.SignUpView.as_view(), name="signup"),
    django.urls.path("activate/<pk>/", users.views.activate, name="activate"),
    django.urls.path("reactivate/<pk>/", users.views.reactivate, name="reactivate"),
    django.urls.path(
        "resend_activation_email",
        users.views.resend_activation_email,
        name="resend_activation_email",
    ),
    django.urls.path("user-profile/<pk>/", users.views.profile_user_view, name="profile-user"),
    django.urls.path("donate/", users.views.donate_view, name="donate"),
]

virtual_cemetery/virtual_cemetery/urls.py
import django.contrib
import django.urls
import django.views

urlpatterns = [
    django.urls.path("admin/", django.contrib.admin.site.urls),
    django.urls.path("", django.urls.include("homepage.urls")),
    django.urls.path("about/", django.urls.include("about.urls")),
    django.urls.path("animals/", django.urls.include("animals.urls")),
    django.urls.path("users/", django.urls.include("users.urls")),
    django.urls.path("event/", django.urls.include("event.urls")),
    django.urls.path("faq/", django.urls.include("faq.urls")),
    django.urls.path("feedback/", django.urls.include("feedback.urls")),
    django.urls.path(
        "set-language/",
        django.views.i18n.set_language,
        name="set-language",
    ),
]

if django.conf.settings.DEBUG:
    import debug_toolbar
    import django.conf.urls.static

    STATIC_ROOT = django.conf.urls.static.static

    urlpatterns += (
        [
            django.urls.path(
                "__debug__/",
                django.urls.include(debug_toolbar.urls),
            ),
        ]
        + STATIC_ROOT(
            django.conf.settings.STATIC_URL,
            document_root=django.conf.settings.STATICFILES_DIRS,
        )
        + STATIC_ROOT(
            django.conf.settings.MEDIA_URL,
            document_root=django.conf.settings.MEDIA_ROOT,
        )
    )

virtual_cemetery/users/forms.py
import django.contrib.auth
import django.forms
import django.utils.translation as translation

import core.forms
import users.managers
import users.models


class CustomPasswordChangeForm(
    core.forms.BootstrapFormMixin,
    django.contrib.auth.forms.PasswordChangeForm,
):
    pass


class CustomPasswordResetForm(
    core.forms.BootstrapFormMixin,
    django.contrib.auth.forms.PasswordResetForm,
):
    """
    Проверка на существование пользователя с указанной почтой в форме
    """

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            django.contrib.auth.models.User.objects.get(email=email)
        except django.core.exceptions.ObjectDoesNotExist:
            raise django.forms.ValidationError(
                translation.gettext_lazy("Пользователь с указанной почтой не найден"),
                code="invalid_email",
            )
        return email


class CustomUserCreationForm(
    core.forms.BootstrapFormMixin,
    django.contrib.auth.forms.UserCreationForm,
):
    class Meta(django.contrib.auth.forms.UserCreationForm.Meta):
        model = django.contrib.auth.models.User
        fields = (
            django.contrib.auth.models.User.email.field.name,
            django.contrib.auth.models.User.username.field.name,
        )

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = users.managers.UserManager.normalize_email(user.email)
        if commit:
            user.save()

        return user

    def clean(self):
        cleaned_data = super().clean()
        if django.contrib.auth.models.User.objects.filter(email=cleaned_data.get("email")).exists():
            self.add_error("email", "Эта почта уже зарегестрированна")
        return cleaned_data


class AuthForm(
    core.forms.BootstrapFormMixin,
    django.contrib.auth.forms.AuthenticationForm,
):
    class Meta:
        model = users.models.User
        fields = (
            django.contrib.auth.models.User.username.field.name,
            django.contrib.auth.models.User.password.field.name,
        )

        labels = {
            django.contrib.auth.models.User.username.field.name: "Имя пользователя/Почта",
            django.contrib.auth.models.User.password.field.name: "Пароль",
        }


class ChangeProfile(
    core.forms.BootstrapFormMixin,
    django.forms.ModelForm,
):
    class Meta:
        model = users.models.Profile
        fields = [
            users.models.Profile.avatar.field.name,
        ]


class UserChangeForm(
    core.forms.BootstrapFormMixin,
    django.contrib.auth.forms.UserChangeForm,
):
    password = None

    class Meta(django.contrib.auth.forms.UserChangeForm.Meta):
        fields = [
            django.contrib.auth.models.User.first_name.field.name,
            django.contrib.auth.models.User.email.field.name,
        ]
        exclude = [
            django.contrib.auth.models.User.password.field.name,
        ]

virtual_cemetery/users/views.py
import datetime

import django.conf
import django.contrib
import django.contrib.auth.decorators
import django.contrib.auth.forms
import django.contrib.auth.models
import django.contrib.auth.views
import django.core.exceptions
import django.core.mail
import django.forms
import django.shortcuts
import django.template
import django.template.loader
import django.urls
import django.utils
import django.utils.translation as translation
import django.views

import animals.models
import feedback.models
import users.forms
import users.models


class CustomPasswordResetView(django.contrib.auth.views.PasswordResetView):
    form_class = users.forms.CustomPasswordResetForm


class CustomPasswordChangeView(django.contrib.auth.views.PasswordChangeView):
    form_class = users.forms.CustomPasswordChangeForm


def donate_view(request):
    template = "users/donate.html"
    return django.shortcuts.render(request, template)


@django.contrib.auth.decorators.login_required(login_url="users:login")
def profile_user(request):
    user = request.user
    template = "users/profile/profile_user.html"

    posts = animals.models.Animal.objects.get_animal_current_user(request.user)
    feedbacks = feedback.models.Feedback.objects.get_feedbacks_list(request.user)

    context = {
        "user": user,
        "posts": posts,
        "feedbacks": feedbacks,
    }

    return django.shortcuts.render(request, template, context)


@django.contrib.auth.decorators.login_required(login_url="users:login")
def profile_user_view(request, pk):
    profile = django.shortcuts.get_object_or_404(
        users.models.Profile.objects.select_related("user"),
        user_id=pk,
    )
    user = profile.user
    posts = animals.models.Animal.objects.get_animal_current_user(user)
    context = {
        "profile": profile,
        "posts": posts,
    }

    return django.shortcuts.render(request, "users/profile/profile_user_view.html", context)


@django.contrib.auth.decorators.login_required(login_url="users:login")
def profile_user_change(request):
    template = "users/profile/profile_user_change.html"

    if request.method == "POST":
        profile_form = users.forms.ChangeProfile(
            request.POST or None,
            request.FILES or None,
            instance=request.user.profile,
        )
        user_form = users.forms.UserChangeForm(
            request.POST or None,
            instance=request.user,
        )

        if profile_form.is_valid() and user_form.is_valid():
            profile_form.save()
            user_form.save()
            django.contrib.messages.success(
                request,
                translation.gettext_lazy(
                    "Настройки успешно сохранены",
                ),
            )
            return django.shortcuts.redirect("users:profile")
    else:
        profile_form = users.forms.ChangeProfile(instance=request.user.profile)
        user_form = users.forms.UserChangeForm(instance=request.user)

    return django.shortcuts.render(
        request,
        template,
        {"profile_form": profile_form, "user_form": user_form},
    )


class SignUpView(django.views.View):
    def get(self, request):
        form = users.forms.CustomUserCreationForm()
        return django.shortcuts.render(request, "users/signup/signup.html", {"form": form})

    def post(self, request):
        form = users.forms.CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = django.conf.settings.DEFAULT_USER_IS_ACTIVE
            user.save()
            profile = users.models.Profile.objects.create(user=user)
            profile.save()

            activate_url = request.build_absolute_uri(
                django.urls.reverse(
                    "users:activate",
                    kwargs={"pk": user.id},
                ),
            )
            django.contrib.messages.warning(
                request,
                translation.gettext_lazy(
                    "Аккаунт зарегистрирован."
                    " Необходимо пройти активацию. Письмо с активацией выслано на указанную при регистрации почту."
                    " Ссылка действительна 12ч.",
                ),
            )
            django.core.mail.send_mail(
                django.template.loader.render_to_string(
                    "users/signup/sent_mail/activate_subject.html",
                ),
                django.template.loader.render_to_string(
                    "users/signup/sent_mail/activate_body.html",
                    {"activate_url": activate_url},
                ),
                django.conf.settings.DEFAULT_FROM_EMAIL,
                [user.email],
                fail_silently=False,
            )
            return django.shortcuts.redirect("homepage:home")
        else:
            return django.shortcuts.render(request, "users/signup/signup.html", {"form": form})


def activate(request, pk):
    """
    Активация аккаунта пользователя
    """
    user = django.contrib.auth.models.User.objects.get(pk=pk)
    if django.utils.timezone.now() > user.date_joined + datetime.timedelta(hours=12):
        return django.shortcuts.render(request, "users/signup/activate_false.html")

    user.is_active = True
    user.save()
    django.contrib.messages.success(
        request,
        translation.gettext_lazy(
            "Аккаунт успешно активирован.",
        ),
    )
    return django.shortcuts.render(request, "users/signup/activate_true.html")


def reactivate(request, pk):
    """
    Разблокировка аккаунта пользователя (повторная активация)
    """
    user = users.models.User.objects.get(pk=pk)
    if user.profile.block_date + datetime.timedelta(days=7) > django.utils.timezone.now():
        user.is_active = True
        user.save()

    django.contrib.messages.success(
        request,
        translation.gettext_lazy(
            "Аккаунт успешно разблокирован. Выполните повторный вход.",
        ),
    )
    return django.shortcuts.redirect(django.urls.reverse("homepage:home"))


def resend_activation_email(request):
    if request.method == "POST":
        username = request.POST["username"]
        try:
            if "@" in username:
                user = users.models.User.objects.by_mail(username)
            else:
                user = users.models.User.objects.get(username=username)
            if user is not None and not user.is_active:
                activate_url = request.build_absolute_uri(
                    django.urls.reverse(
                        "users:reactivate",
                        kwargs={"pk": user.id},
                    ),
                )
                django.core.mail.send_mail(
                    django.template.loader.render_to_string(
                        "users/login/sent_mail/reactivate_subject.txt",
                    ),
                    django.template.loader.render_to_string(
                        "users/login/sent_mail/reactivate_body.html",
                        {"activate_url": activate_url},
                    ),
                    django.conf.settings.DEFAULT_FROM_EMAIL,
                    [user.email],
                    fail_silently=False,
                )
                django.contrib.messages.success(request, "Письмо успешно отправлено!")
                request.session["show_resend_button"] = False
        except users.models.User.DoesNotExist:
            django.contrib.messages.error(request, "Аккаунт не найден!")
            return django.shortcuts.redirect("users:login")

    return django.shortcuts.redirect("users:login")

virtual_cemetery/templates/users/profile/profile_user.html
<!DOCTYPE html>
{% extends 'base/base.html' %}
{% load static %}

{% block title %}cloudpets - Профиль пользователя{% endblock title %}

{% block content %}
{% include "includes/messages.html" %}
<div class="row">
    {% if user.profile.avatar %}
    <div class="col-md-2">
        <div class="card shadow mb-2 h-100">
            <div class="card-body d-flex justify-content-center align-items-center">
                <img src="{{ user.profile.get_image_300x300.url }}" alt="Avatar" class="img-thumbnail">
            </div>
        </div>
    </div>
    {% endif %}
    <div class="col-md-10">
        <div class="card border-0 shadow h-100">
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h2 class="card-title mb-0">
                        {% if user.first_name %}
                        {{ user.first_name }}
                        {% else %}
                        {{ user.email }}
                        {% endif %}
                    </h2>
                    <div class="btn-group" role="group">
                        <a href="{% url 'users:profile_settings' %}" class="btn btn-primary ">Настройки</a>
                        <a href="{% url 'users:password-change' %}" class="btn btn-danger">Сменить пароль</a>
                    </div>
                </div>
                <hr>
                <p class="card-text"><strong>Эл. почта:</strong> {{ user.email }}</p>
            </div>
        </div>
    </div>
</div>
{% if posts %}
<div class="row mt-4">
    <div class="col-md-12">
        <div class="card border-0 shadow">
            <div class="card-body">
                <h3>Ваши публикации:</h3>
                <div class="row">
                    {% for post in posts %}
                    <div class="col-md-3 mb-3">
                        <div class="card shadow">
                            {% if post.main_image %}
                            <img src="{{ post.get_image_200x200.url }}" class="card-img-top" alt="Post Image">
                            {% endif %}
                            <div class="card-body">
                                <h5 class="card-title">{{ post.name }}</h5>
                            </div>
                            <div class="card-footer">
                                <a href="{% url 'animals:animal-detail' post.pk %}" class="btn btn-primary stretched-link">Подробнее</a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock content %}

virtual_cemetery/templates/users/profile/profile_user_change.html
<!DOCTYPE html>
{% extends 'base/base.html' %}
{% load static %}

{% block title %}cloudpets - Настройки пользователя{% endblock title %}

{% block content %}
{% include "includes/messages.html" %}
<div class="row">
  <div class="col-md-6 offset-md-3">
    <div class="card shadow">
      <div class="card-body">
        <h3 class="card-title text-center mb-4">Настройки</h3>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ profile_form.as_p }}
            {{ user_form.as_p }}
            <button type="submit" class="btn btn-warning btn-block mt-4">Сохранить</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

virtual_cemetery/templates/users/profile/profile_user_view.html
<!DOCTYPE html>
{% extends 'base/base.html' %}
{% load static %}

{% block title %}cloudpets - Просмотр профиля пользователя{% endblock title %}

{% block content %}
{% include "includes/messages.html" %}
<div class="row">
    {% if profile.avatar %}
    <div class="col-md-2">
        <div class="card shadow mb-2 h-100">
            <div class="card-body d-flex justify-content-center align-items-center">
                <img src="{{ profile.get_image_300x300.url }}" alt="Avatar" class="img-thumbnail">
            </div>
        </div>
    </div>
    {% endif %}
    <div class="col-md-10">
        <div class="card border-0 shadow h-100">
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h2 class="card-title mb-0">
                        {% if profile.user.first_name %}
                        {{ profile.user.first_name }}
                        {% else %}
                        {{ profile.user.email }}
                        {% endif %}
                    </h2>
                </div>
                <hr>
                <p class="card-text"><strong>Эл. почта:</strong> {{ profile.user.email }}</p>
            </div>
        </div>
    </div>
</div>
{% if posts %}
<div class="row mt-4">
    <div class="col-md-12">
        <div class="card border-0 shadow">
            <div class="card-body">
                <h3>Публикации пользователя:</h3>
                <div class="row">
                    {% for post in posts %}
                    <div class="col-md-3 mb-3">
                        <div class="card shadow">
                            {% if post.main_image %}
                            <img src="{{ post.get_image_200x200.url }}" class="card-img-top" alt="Post Image">
                            {% endif %}
                            <div class="card-body">
                                <h5 class="card-title">{{ post.name }}</h5>
                            </div>
                            <div class="card-footer">
                                <a href="{% url 'animals:animal-detail' post.pk %}" class="btn btn-primary stretched-link">Подробнее</a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock content %}