virtual_cemetery/animals/urls.py
import django.urls

import animals.views

app_name = "animals"

urlpatterns = [
    django.urls.path("detail/<pk>/", animals.views.animal_detail, name="animal-detail"),
    django.urls.path("add-new-animal/", animals.views.add_new_animal, name="add-animal"),
    django.urls.path("change/<pk>/", animals.views.change_current_animal, name="change-animal"),
    django.urls.path("delete-comment/<pk>/", animals.views.delete_comment, name="delete-comment"),
    django.urls.path("delete-animal/<pk>/", animals.views.delete_animal, name="delete-animal"),
]

virtual_cemetery/event/urls.py
import django.urls

import event.views

app_name = "event"

urlpatterns = [
    django.urls.path("all/", event.views.all_events_view, name="all-events"),
    django.urls.path("register/", event.views.registration_event_work, name="register-work"),
    django.urls.path("work/<int:pk>/", event.views.get_current_work_event, name="current-work"),
    django.urls.path("<int:pk>/", event.views.get_current_event_view, name="current-event"),
]

virtual_cemetery/faq/urls.py
import django.urls

import faq.views

app_name = "faq"

urlpatterns = [
    django.urls.path("", faq.views.faq_view, name="faq"),
]

virtual_cemetery/users/urls.py
import django.contrib.auth.views as auth_views
import django.forms
import django.urls


import users.forms
import users.views

app_name = "users"

urlpatterns = [
    django.urls.path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="users/login/login.html",
            authentication_form=users.forms.AuthForm,
        ),
        name="login",
    ),
    django.urls.path(
        "logout/",
        auth_views.LogoutView.as_view(
            template_name="users/login/logout.html",
        ),
        name="logout",
    ),
    django.urls.path(
        "password-reset/",
        users.views.CustomPasswordResetView.as_view(
            template_name="users/reset_password/password_reset_form.html",
            email_template_name="users/reset_password/sent_mail/password_reset_email.html",
            subject_template_name="users/reset_password/sent_mail/password_reset_subject.txt",
            success_url=django.urls.reverse_lazy(
                "users:password-reset-done",
            ),
        ),
        name="password-reset",
    ),
    django.urls.path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/reset_password/password_reset_done.html",
        ),
        name="password-reset-done",
    ),
    django.urls.path(
        "password-reset/confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="users/reset_password/password_reset_confirm.html",
            success_url=django.urls.reverse_lazy(
                "users:password-reset-complete",
            ),
        ),
        name="password-reset-confirm",
    ),
    django.urls.path(
        "password-reset/complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/reset_password/password_reset_complete.html",
        ),
        name="password-reset-complete",
    ),
    django.urls.path(
        "password-change/",
        users.views.CustomPasswordChangeView.as_view(
            template_name="users/change_password/password_change.html",
            success_url=django.urls.reverse_lazy(
                "users:password-change-done",
            ),
        ),
        name="password-change",
    ),
    django.urls.path(
        "password-change/done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="users/change_password/password_change_done.html",
        ),
        name="password-change-done",
    ),
    django.urls.path("profile/", users.views.profile_user, name="profile"),
    django.urls.path("profile/settings/", users.views.profile_user_change, name="profile_settings"),
    django.urls.path("signup/", users.views.SignUpView.as_view(), name="signup"),
    django.urls.path("activate/<pk>/", users.views.activate, name="activate"),
    django.urls.path("reactivate/<pk>/", users.views.reactivate, name="reactivate"),
    django.urls.path(
        "resend_activation_email",
        users.views.resend_activation_email,
        name="resend_activation_email",
    ),
    django.urls.path("user-profile/<pk>/", users.views.profile_user_view, name="profile-user"),
    django.urls.path("donate/", users.views.donate_view, name="donate"),
]

virtual_cemetery/virtual_cemetery/urls.py
import django.contrib
import django.urls
import django.views

urlpatterns = [
    django.urls.path("admin/", django.contrib.admin.site.urls),
    django.urls.path("", django.urls.include("homepage.urls")),
    django.urls.path("about/", django.urls.include("about.urls")),
    django.urls.path("animals/", django.urls.include("animals.urls")),
    django.urls.path("users/", django.urls.include("users.urls")),
    django.urls.path("event/", django.urls.include("event.urls")),
    django.urls.path("faq/", django.urls.include("faq.urls")),
    django.urls.path("feedback/", django.urls.include("feedback.urls")),
    django.urls.path(
        "set-language/",
        django.views.i18n.set_language,
        name="set-language",
    ),
]

if django.conf.settings.DEBUG:
    import debug_toolbar
    import django.conf.urls.static

    STATIC_ROOT = django.conf.urls.static.static

    urlpatterns += (
        [
            django.urls.path(
                "__debug__/",
                django.urls.include(debug_toolbar.urls),
            ),
        ]
        + STATIC_ROOT(
            django.conf.settings.STATIC_URL,
            document_root=django.conf.settings.STATICFILES_DIRS,
        )
        + STATIC_ROOT(
            django.conf.settings.MEDIA_URL,
            document_root=django.conf.settings.MEDIA_ROOT,
        )
    )

virtual_cemetery/animals/models.py
import pathlib
import uuid

import django.contrib.auth
import django.core.validators
import django.db
import django.forms
import django.utils.translation as translation
import sorl.thumbnail

import animals.managers
import core.models


def item_directory_path(instance, filename):
    ext = filename.split(".")[-1]
    animal_id = str(instance.pk) if instance.pk else str(uuid.uuid4())
    filename = f"{animal_id}.{ext}"
    return pathlib.Path("animals") / animal_id / filename


class Animal(core.models.AbstractModel):
    objects = animals.managers.AnimalManager()

    user = django.db.models.ForeignKey(
        django.contrib.auth.models.User,
        on_delete=django.db.models.CASCADE,
        related_name="animals",
    )
    name = django.db.models.CharField(
        translation.gettext_lazy("имя питомца"),
        max_length=70,
        help_text=translation.gettext_lazy("Введите имя вашего питомца"),
    )
    biography = django.db.models.TextField(
        translation.gettext_lazy("биография питомца"),
        max_length=1200,
        help_text=translation.gettext_lazy("Введите биографию вашего питомца"),
        null=True,
        blank=True,
    )
    date_of_birth = django.db.models.DateField(
        translation.gettext_lazy("дата рождения"),
        help_text=translation.gettext_lazy("Введите дату рождения вашего питомца"),
        blank=True,
        null=True,
    )
    date_of_death = django.db.models.DateField(
        translation.gettext_lazy("дата смерти"),
        help_text=translation.gettext_lazy("Введите дату смерти вашего питомца"),
        blank=True,
        null=True,
    )
    main_image = sorl.thumbnail.ImageField(
        translation.gettext_lazy("Изображение питомца"),
        help_text=translation.gettext_lazy("Загрузите изображение вашего питомца"),
        upload_to=item_directory_path,
    )

    class Meta:
        ordering = ("name",)
        verbose_name = translation.gettext_lazy("питомец")
        verbose_name_plural = translation.gettext_lazy("питомцы")

    def __str__(self):
        return self.name

    def get_image_200x200(self):
        return sorl.thumbnail.get_thumbnail(
            self.main_image,
            "200x200",
            crop="center",
            quality=51,
        )

    def get_image_500x500(self):
        return sorl.thumbnail.get_thumbnail(
            self.main_image,
            "500x500",
            crop="center",
            quality=100,
        )

    def image_tmb(self):
        if self.main_image:
            return django.utils.html.mark_safe(
                f"<img src='{self.get_image_200x200().url}' width='50'>",
            )

        return translation.gettext_lazy("Нет изображения питомца")

    image_tmb.short_description = translation.gettext_lazy("превью")
    image_tmb.allow_tags = True
    image_tmb.field_name = "image_tmb"


class AnimalComments(core.models.AbstractModel):
    animal = django.db.models.ForeignKey(
        Animal,
        on_delete=django.db.models.CASCADE,
        related_name="animal_comments",
    )
    user = django.db.models.ForeignKey(
        django.contrib.auth.models.User,
        on_delete=django.db.models.CASCADE,
    )
    comment = django.db.models.CharField(
        translation.gettext_lazy("комментарий"),
        max_length=200,
        help_text=translation.gettext_lazy("Введите комментарий"),
    )

    class Meta:
        ordering = ("user",)
        verbose_name = translation.gettext_lazy("комментарий")
        verbose_name_plural = translation.gettext_lazy("комментарии")

virtual_cemetery/animals/forms.py
import django.contrib.auth.forms
import django.contrib.auth.models
import django.forms

import animals.models


class BootstrapFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fieldn in self.visible_fields():
            fieldn.field.widget.attrs["class"] = "form-control"


class AddNewAnimalForm(BootstrapFormMixin, django.forms.ModelForm):
    class Meta:
        model = animals.models.Animal
        fields = (
            animals.models.Animal.name.field.name,
            animals.models.Animal.biography.field.name,
            animals.models.Animal.main_image.field.name,
            animals.models.Animal.date_of_birth.field.name,
            animals.models.Animal.date_of_death.field.name,
        )

    date_of_birth = django.forms.DateField(
        label="Дата рождения",
        help_text="Введите дату рождения вашего питомца",
        widget=django.forms.widgets.SelectDateWidget(),
        required=False,
    )
    date_of_death = django.forms.DateField(
        label="Дата смерти",
        help_text="Введите дату смерти вашего питомца",
        widget=django.forms.widgets.SelectDateWidget(),
        required=False,
    )


class AddNewAnimalComment(BootstrapFormMixin, django.forms.ModelForm):
    class Meta:
        model = animals.models.AnimalComments
        fields = (animals.models.AnimalComments.comment.field.name,)

virtual_cemetery/animals/views.py
import django.conf
import django.contrib
import django.contrib.auth.decorators
import django.shortcuts
import django.utils.translation as translation

import animals.forms
import animals.models


def homepage_animals_view(request):
    template = "homepage/home.html"
    all_animals = animals.models.Animal.objects.get_animals_list()

    context = {
        "animals": all_animals,
    }

    return django.shortcuts.render(request, template, context)


def animal_detail(request, pk):
    template = "animals/animal_detail.html"
    animal = animals.models.Animal.objects.get_animal_detail(pk=pk)

    if request.method == "POST":
        form = animals.forms.AddNewAnimalComment(request.POST)
        if form.is_valid():
            if request.user == animal.user:
                django.contrib.messages.error(
                    request,
                    "Вы не можете оставлять комментарии к своим собственным постам.",
                )
                return django.shortcuts.redirect("animals:animal-detail", pk=pk)

            if animal.animal_comments.filter(user=request.user).exists():
                django.contrib.messages.error(request, "Вы уже оставили комментарий к этому посту.")
                return django.shortcuts.redirect("animals:animal-detail", pk=pk)

            animal_comment = form.save(commit=False)
            animal_comment.user = request.user
            animal_comment.animal_id = animal.pk
            animal_comment.save()

            django.contrib.messages.success(
                request,
                translation.gettext_lazy(
                    "Комментарий успешно оставлен",
                ),
            )

            return django.shortcuts.redirect("animals:animal-detail", pk=animal.pk)
    else:
        form = animals.forms.AddNewAnimalComment()

    context = {
        "animal": animal,
        "form": form,
    }

    return django.shortcuts.render(request, template, context)


def delete_comment(request, pk):
    comment = django.shortcuts.get_object_or_404(animals.models.AnimalComments, pk=pk)
    if comment.user == request.user:
        comment.delete()
        django.contrib.messages.success(
            request,
            "Комментарий успешно удален",
        )

    return django.shortcuts.redirect("animals:animal-detail", pk=comment.animal.pk)


def delete_animal(request, pk):
    animal = django.shortcuts.get_object_or_404(animals.models.Animal, pk=pk)
    if animal.user == request.user:
        animal.delete()
        django.contrib.messages.success(
            request,
            "Пост успешно удален.",
        )

    return django.shortcuts.redirect("homepage:home")


@django.contrib.auth.decorators.login_required(login_url="users:login")
def add_new_animal(request):
    template = "animals/add_new_animal.html"

    if request.method == "POST":
        form = animals.forms.AddNewAnimalForm(request.POST, request.FILES)
        if form.is_valid():
            new_animal = form.save(commit=False)
            new_animal.user = request.user
            new_animal.save()

            django.contrib.messages.success(
                request,
                translation.gettext_lazy(
                    "Новый пост успешно добавлен.",
                ),
            )

            return django.shortcuts.redirect("animals:animal-detail", pk=new_animal.pk)

    else:
        form = animals.forms.AddNewAnimalForm()

    return django.shortcuts.render(request, template, {"form": form})


@django.contrib.auth.decorators.login_required(login_url="users:login")
def change_current_animal(request, pk):
    animal = django.shortcuts.get_object_or_404(animals.models.Animal, pk=pk)
    template = "animals/change_current_animal.html"

    if request.method == "POST":
        form = animals.forms.AddNewAnimalForm(request.POST, request.FILES, instance=animal)
        if form.is_valid():
            form.save()
            django.contrib.messages.success(
                request,
                translation.gettext_lazy(
                    "Запись отредактирована",
                ),
            )
            return django.shortcuts.redirect("animals:animal-detail", pk=animal.pk)
    else:
        form = animals.forms.AddNewAnimalForm(instance=animal)

    context = {
        "form": form,
        "animal": animal,
    }
    return django.shortcuts.render(request, template, context)

virtual_cemetery/templates/animals/add_new_animal.html
<!DOCTYPE html>
{% extends 'base/base.html' %}
{% load static %}

{% block title %}cloudpets - Создание нового поста{% endblock title %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8">
    <div class="card border-0 shadow-lg">
      <div class="card-body">
            <h3 class="mt-5 mb-4">Создание нового поста</h3>
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {{ form.as_p }}
              <button type="submit" class="w-100 mb-2 btn btn-lg rounded-3 btn-warning ">Создать</button>
          </form>
        </div>
      </div>
    </div>
</div>
{% endblock content %}

virtual_cemetery/templates/animals/animal_detail.html
<!DOCTYPE html>
{% extends 'base/base.html' %}
{% load static %}

{% block title %}cloudpets - Просмотр поста{% endblock title %}

{% block content %}
{% include "includes/messages.html" %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8 text-center">
      <h2 class="mb-4">Примите участие в наших конкурсах</h2>
      <p class="lead">Желаете оставить незабываемый след о вашем питомце? Проявите свою творческую натуру и участвуйте в наших конкурсах!</p>
      <a href="{% url 'event:all-events' %}" class="btn btn-primary btn-lg mt-4">
        <i class="fas fa-trophy mr-2"></i> Перейти к конкурсам
      </a>
    </div>
  </div>
  <hr class="my-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card border-0 shadow-lg">
        {% if animal.main_image %}
        <img src="{{ animal.get_image_500x500.url }}" class="card-img-top" alt="{{ animal.name }}">
        {% endif %}
        <hr>
        {% if animal.user == request.user %}
          <div class="d-flex justify-content-start mb-3">
            <a href="{% url 'animals:change-animal' animal.pk %}" class="btn btn-primary btn-sm mr-2">Редактировать</a>
            <form action="{% url 'animals:delete-animal' animal.pk %}" method="post" class="d-inline">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger btn-sm delete-button" onclick="confirmDeletePost()">Удалить</button>
            </form>
          </div>
        {% endif %}
        <div class="card-body">
          <p class="card-text"><strong>Автор:</strong> <a href="{% url 'users:profile-user' animal.user.pk %}">{{ animal.user.first_name }}</a></p>
          <h5 class="card-title">{{ animal.name }}</h5>
          {% if animal.biography %}
          <p class="card-text">{{ animal.biography }}</p>
          {% endif %}
          <hr>
          <div class="d-flex justify-content-between">
            {% if animal.date_of_birth %}
            <p class="card-text"><strong>Дата рождения:</strong> {{ animal.date_of_birth }}</p>
            {% endif %}
            {% if animal.date_of_death %}
            <p class="card-text"><strong>Дата смерти:</strong> {{ animal.date_of_death }}</p>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row justify-content-center mt-4">
    <div class="col-md-6">
        <div class="card border-0 shadow-lg">
            <div class="card-body">
                <h2 class="mb-4">Комментарии:</h2>
                <div class="mb-4">
                    {% if not request.user == animal.user %}
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ form.comment }}
                        </div>
                        <button type="submit" class="btn btn-warning">Отправить</button>
                    </form>
                    {% endif %}
                </div>
                <ul class="list-unstyled">
                    {% for comment in animal.comments.all %}
                    <li class="media mb-4">
                        <div class="media-body">
                            <h5 class="mt-0"><a href="{% url 'users:profile-user' comment.user.pk %}">{{ comment.user.first_name }}</a></h5>
                            <p>{{ comment.comment }}</p>
                            {% if request.user == comment.user %}
                            <form action="{% url 'animals:delete-comment' comment.pk %}" method="post" class="d-inline">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger btn-sm" onclick="confirmDelete('{{ comment.pk }}')">Удалить</button>
                            </form>
                            {% endif %}
                        </div>
                    </li>
                    {% empty %}
                    <p>Пока никто не прокомментировал данный пост.</p>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
<script>
    function confirmDelete(commentId) {
        if (confirm("Вы уверены, что хотите удалить этот комментарий?")) {
            document.getElementById("deleteForm-" + commentId).submit();
        }
    }
    function confirmDeletePost() {
        if (confirm("Вы уверены, что хотите удалить этот пост?")) {
            document.getElementById("deleteAnimalForm").submit();
        }
    }
</script>
{% endblock %}

virtual_cemetery/templates/animals/change_current_animal.html
<!DOCTYPE html>
{% extends 'base/base.html' %}
{% load static %}

{% block title %}cloudpets - Редактирование публикации{% endblock title %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8">
    <div class="card border-0 shadow-lg">
      <div class="card-body">
        <h3 class="mt-5 mb-4">Отредактируйте вашу запись</h3>
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="w-100 mb-2 btn btn-lg rounded-3 btn-warning ">Сохранить</button>
      </form>
        </div>
      </div>
    </div>
</div>
{% endblock content %}